added ComputeAABB func
shenfy/mineola pull request #27
Opened 2021-01-06 10:50 UTC by soap1984

2021-01-06 16:20 UTC, shenfy requested changes

2021-01-06 16:20 UTC, shenfy commented on src/src/SceneNode.cpp
> +void AABBVertexes(const glm::vec3 &min, const glm::vec3 &max, std::vector<glm::vec3> &vts) {
make this a member function of the AABB class, vector<vec3> AABB::Corners()
add comments to make it more readable.

2021-01-06 16:20 UTC, shenfy commented on src/src/SceneNode.cpp
> +  for (int i = 0; i <= 7; i++) {
use i < 8, so it's more readable to human (8 vertices in a cube)

2021-01-06 16:20 UTC, shenfy commented on src/src/SceneNode.cpp
> +float boolToSign(bool b) {
Bool2Sign

2021-01-06 16:20 UTC, shenfy commented on src/src/SceneNode.cpp
> +      if (renderable->MinVertex() != glm::vec3() || renderable->MaxVertex() != glm::vec3()) {
check is renderable has valid AABB (i.e. unique_ptr is not null). glm::vec3() is a valid vertex value, shouldn't be used as a flag.

2021-01-06 16:20 UTC, shenfy commented on src/src/SceneNode.cpp
> +    glm::vec3 min_node(std::numeric_limits<float>::max()), max_node(std::numeric_limits<float>::lowest());
add a AABB::Combine(const AABB &other) method instead

2021-01-06 16:20 UTC, shenfy commented on src/src/SceneNode.cpp
> +    vts.push_back(center + extent * 0.5f * sign);
use return value of vector<vec3> instead of out parameter.

2021-01-07 07:24 UTC, shenfy requested changes

2021-01-07 07:24 UTC, shenfy commented on src/include/mineola/Renderable.h
> +  glm::vec3 lb_{0.f};
for struct public members, do not use the trailing underscore.

2021-01-07 07:24 UTC, shenfy commented on src/include/mineola/Renderable.h
> +  void SetAABB(const glm::vec3 &lb, const glm::vec3 &ub);
SetAABB should take an AABB as argument

2021-01-07 07:24 UTC, shenfy commented on src/src/Renderable.cpp
> +  auto corners = std::vector<glm::vec3>();
for fixed length array, set its length at construction time.

2021-01-07 07:24 UTC, shenfy commented on src/src/Renderable.cpp
> +const std::unique_ptr<AABB> &Renderable::GetAABB() const {
name it AABB instead of GetAABB

2021-01-07 07:24 UTC, shenfy commented on src/src/SceneNode.cpp
> +    glm::vec3 min_node(std::numeric_limits<float>::max()), max_node(std::numeric_limits<float>::lowest());
remove unused variables

2021-01-07 07:24 UTC, shenfy commented on src/src/SceneNode.cpp
> +    bbox_node.lb_ = glm::vec3(std::numeric_limits<float>::max());
use the AABB(lb, ub) constructor

2021-01-07 07:24 UTC, shenfy commented on src/src/SceneNode.cpp
> +void SceneNode::ComputeAABB(glm::vec3 &center, glm::vec3 &extent) {
return an AABB instead.

2021-01-11 08:01 UTC, chubei requested changes

2021-01-11 09:08 UTC, chubei commented on src/src/SceneNode.cpp
> +}
std::optional<AABB> result;
for (auto &child: children) {
  auto aabb = child.ComputeAABB();
  if (aabb) {
    if (result) {
      result.Combine(aabb);
    } else {
      result = aabb;
    }
  }
}

if (result) {
    // apply model mat
}

return result;

2021-01-12 10:14 UTC, chubei-oppen requested changes

2021-01-12 10:14 UTC, chubei-oppen commented on src/src/Renderable.cpp
> -
don't remove this blank line

2021-01-12 10:14 UTC, chubei-oppen commented on src/include/mineola/Renderable.h
> +  std::optional<AABB> Bbox() const;
const std::optional<AABB> &

2021-01-12 10:14 UTC, chubei-oppen commented on src/src/SceneNode.cpp
> +
remove dead code

2021-01-12 10:52 UTC, chubei-oppen approved these changes

2021-01-12 10:53 UTC, merged